### ISSUE TITLE
Add NIST-linearized temperature calculation

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_MAX31855#12]
The older version of this library had a temperature calculation feature that used raw voltages from the thermocouple and cold junction. See here:
https://github.com/adafruit/Adafruit_Python_MAX31855/blob/master/Adafruit_MAX31855/MAX31855.py#L99

**NOTE** - it might not be correct as is. See this issue:
https://github.com/adafruit/Adafruit_Python_MAX31855/issues/5
and this PR:
https://github.com/adafruit/Adafruit_Python_MAX31855/pull/7

And some more info here:
https://learn.adafruit.com/calibrating-sensors/maxim-31855-linearization

It might be worth adding that feature to this library.

**Comment by ladyada** [comment]
SMASH THAT CLOSE BUTTON!
