### ISSUE TITLE
Multiple MAX31855 Modules running on Pi Zero

### ISSUE THREAD

**Issue by NoSvOrAx** [adafruit/Adafruit_CircuitPython_MAX31855#21]
So I have a project here that requires two of the MAX31855 modules.  Everything works as expected with 1 unit, but with 2 units, unit 2 gives erroneous readings that appear to randomly switch from the expected reading for unit 2, the expected/actual reading of unit 1, and sometimes what appears to be the sum of the expected readings of 1 and 2.

All of the references I can find for using multiple units refer to the deprecated version of this library, including the guide from the product page (In the FAQ section).

I did hit up the discord to see if anyone else was having issues like this, but no joy was to be had.  Not a lot of code here for me to mess up so I figure it must be something under the hood.  I tried changing up CS pins, importing the library using "as" to give it different names, and using tc1.temperature_NIST, all without any change output behavior.  Commenting out the two lines for either TC leaves the other working perfectly.

The code:
```python
import time
import board
import busio
import digitalio
import adafruit_max31855

spi = busio.SPI(board.SCK, MOSI=board.MOSI, MISO=board.MISO)
cs1 = digitalio.DigitalInOut(board.D8)
cs2 = digitalio.DigitalInOut(board.D26)

tc1 = adafruit_max31855.MAX31855(spi, cs1)
tc2 = adafruit_max31855.MAX31855(spi, cs2)

while True:
    print('Thermocouple 1: {} degrees C'.format(tc1.temperature))
    print('Thermocouple 2: {} degrees C'.format(tc2.temperature))
    time.sleep(1)
```

**Comment by ladyada** [comment]
what if you put a delay between the reads?

**Comment by ladyada** [comment]
also do not use D8 or D7

**Comment by NoSvOrAx** [comment]
D8 was the problem, no wait needed.

You are amazing!  Love the products!
